services:
  backend:
    image: local-backend:latest
    container_name: backend
    restart: unless-stopped
    networks:
      - traefik-vpc
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`hello-backend.world`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=3000
networks:
  traefik-vpc:
    external: true
