services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    ports:
      - "81:81"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
networks:
  frontend:
    external: true
